# Generated by Django 5.0.4 on 2024-04-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_post_descipcion'),
        ('news', '0002_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='history_posts', to='history.category', verbose_name='Categorías'),
        ),
    ]
