# Generated by Django 5.0.4 on 2024-04-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_categories_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
