# Generated by Django 5.0.4 on 2024-04-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiovisual', '0003_rename_categories_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
