# Generated by Django 5.0.4 on 2024-04-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='imagegenes',
        ),
    ]
