# Generated by Django 5.0.4 on 2024-04-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_rename_image_postimage_imagegenes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='imagegenes',
            new_name='image',
        ),
    ]
