# Generated by Django 5.0.4 on 2024-04-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_post_descripcion_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='descripcion',
        ),
    ]
