# Generated by Django 5.0.4 on 2024-04-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_remove_post_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descipcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
    ]
