# Generated by Django 5.0.4 on 2024-04-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Direccion del Proyecto'),
        ),
    ]
