# Generated by Django 5.0.4 on 2024-04-25 17:08

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_rename_categories_post_category_and_more'),
        ('project', '0003_delete_category_alter_post_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='proyect_posts', to='history.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Datos'),
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Ingrese el enlace del video de Vimeo', null=True, verbose_name='Enlace del video'),
        ),
    ]
