# Generated by Django 5.0.4 on 2024-04-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_post_data_remove_post_video_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
